### ISSUE TITLE
Titlul proiectului

### ISSUE THREAD

**Issue by georgianaungureanu** [Moldoteck/TeamProject#15]

**Comment by georgianaungureanu** [comment]
https://doodle.com/poll/sq4yhgwh34cpcizx aici puteți vota ideea de titlu care vi se pare mai potrivită

**Comment by Moldoteck** [comment]
Mai propun o varianta: Netbooking: Chirii de neuitat

**Comment by georgianaungureanu** [comment]
Cum nu s-a votat titlul, propun ca varianta finala să fie: 
easybooking: Modalitate eficientă de a da spre închiriere sau de a închiria o locuință
