### ISSUE TITLE
Diagrame UML de activitate

### ISSUE THREAD

**Issue by georgianaungureanu** [Moldoteck/TeamProject#17]

**Comment by georgianaungureanu** [comment]
https://drive.google.com/file/d/11GUmKtnXAsjM9q6xIo49FHi5Fj1v--kM/view?usp=sharing Diagrama UML de activitate

**Comment by Moldoteck** [comment]
Fă pls un export în .png sau .jpg, că nu îl pot deschide

**Comment by georgianaungureanu** [comment]
![diagrama uml de activitate](https://user-images.githubusercontent.com/37276011/37602675-e37fc9c0-2b9d-11e8-9f27-84a72ad1d5e0.jpg)

**Comment by georgianaungureanu** [comment]
https://docs.google.com/document/d/1yMixBGFTxkqPvV4wbyvcIMLGadmzu7afUwgBQYFY7nA/edit?usp=sharing aici este și descrierea diagramei UML de activitate
